// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestionDeEstudiantes.WEB.Entities
{
    public partial class DetalleCalificaciones
    {
        public int Id { get; set; }
        public int IdCalificacion { get; set; }
        public int IdEstudiante { get; set; }
        public int? Calificacion { get; set; }
        public string CalificacionLiteral { get; set; }
        public DateTime FechaCreacion { get; set; }

        public virtual Calificaciones IdCalificacionNavigation { get; set; }
        public virtual Estudiantes IdEstudianteNavigation { get; set; }
    }
}