// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestionDeEstudiantes.WEB.Entities
{
    public partial class Estudiantes
    {
        public Estudiantes()
        {
            DetalleCalificaciones = new HashSet<DetalleCalificaciones>();
            PaseDeLista = new HashSet<PaseDeLista>();
        }

        public int Id { get; set; }
        public int IdColegio { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string LugarNacimiento { get; set; }
        public string Sexo { get; set; }
        public string Foto { get; set; }
        public bool Activo { get; set; }
        public DateTime FechaCreacion { get; set; }

        public virtual Colegios IdColegioNavigation { get; set; }
        public virtual ICollection<DetalleCalificaciones> DetalleCalificaciones { get; set; }
        public virtual ICollection<PaseDeLista> PaseDeLista { get; set; }
    }
}