// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestionDeEstudiantes.WEB.Entities
{
    public partial class PaseDeLista
    {
        public int Id { get; set; }
        public int IdEstudiante { get; set; }
        public DateTime Fecha { get; set; }
        public int IdOpcion { get; set; }
        public DateTime FechaCreacion { get; set; }

        public virtual Estudiantes IdEstudianteNavigation { get; set; }
        public virtual PaseDeListaOpciones IdOpcionNavigation { get; set; }
    }
}