// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GestionDeEstudiantes.WEB.Entities
{
    public partial class Usuarios
    {
        public Usuarios()
        {
            Materias = new HashSet<Materias>();
        }

        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public string CorreoElectronico { get; set; }
        public int? IdRol { get; set; }
        public bool Activo { get; set; }
        public DateTime FechaCreacion { get; set; }
        public string NombreCompleto { get; set; }

        public virtual Roles IdRolNavigation { get; set; }
        public virtual ICollection<Materias> Materias { get; set; }
    }
}